<h1>Jokes</h1>
<!-- Indicates a successful or positive action -->
<?php echo $this->jokeactions(null, array('add' => $this->translate('Add a new Joke'))); ?>
<table class="table">
    <thead>
        <tr>
            <th>Title</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($jokes as $joke): ?>
        <tr>
            <td>
                <?php $url = $this->url('joke',array('id' => $joke->getId(), 'slug' => $joke->getTitle())); ?>
                <a href=" <?php echo $url ?>"><?php echo $joke->getTitle() ?></a>
            </td>
            <td>
                <?php echo $this->jokeactions($joke , array(
                    'edit' => $this->translate('Edit'),
                    'delete' => $this->translate('Delete')
                    ));
                ?>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>