<h1>Jokes</h1>
<!-- Indicates a successful or positive action -->
<a class="btn btn-success" href="<?php echo $this->url('jokes:add'); ?>" role="button"><?php echo $this->translate('Add a new Joke') ?></a>
<table class="table">
    <thead>
        <tr>
            <th>Title</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($jokes as $joke): ?>
        <tr>
            <td>
                <?php $url = $this->url('joke',array('id' => $joke->getId(), 'slug' => $joke->getTitle())); ?>
                <a href=" <?php echo $url ?>"><?php echo $joke->getTitle() ?></a>
            </td>
            <td>
                <a class="btn btn-default" href="<?php echo $this->url('jokes/edit', array("id"=> $joke->getId())); ?>" role="button"><?php echo $this->translate('Edit') ?></a>
                <a class="btn btn-danger" href="<?php echo $this->url('jokes/delete', array("id"=> $joke->getId())); ?>" role="button"><?php echo $this->translate('Delete') ?></a>
            </td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>