<h1>Credits</h1>
<p class="bg-info">This sample project uses numerous open source works, a big thank you to their authors.</p>
<dl>
    <dt><a href="http://thenounproject.com/term/smile/31242/">Smile Icon</a></dt>
    <dd>Smile designed by <a href="http://thenounproject.com/SimpleIcons/">Simple Icons</a> from the <a
            href="http://thenounproject.com">Noun Project</a>. We used it as a favicon and as the sample project icon.</dd>
</dl>